### ISSUE TITLE
#toast-container width 100% bug  

### ISSUE THREAD

**Issue by openainext** [CodeSeven/toastr#228]
add css

``` css
 #toast-container{
     position: absolute;
     width: 300px;
   }
   .toast-top-center,.toast-bottom-center{
    left:50%;
    margin-left: -150px;
   }
   .toast-top-full-width,.toast-bottom-full-width{
    width: 100%!important;
   }
```
