### ISSUE TITLE
Toasts prevent clicking of background elements

### ISSUE THREAD

**Issue by leniel** [CodeSeven/toastr#235]
The way it is now, the menu behind the toast is unclickable.

The following style complements it and fixes the issue. Just add it to your own .css file or in the future it could make it into a new toastr version. :)

``` css
.toast-top-center
{
    width: 300px;
    margin: 0 auto;
    left: 0;
}
```
