### ISSUE TITLE
Latest version has a slight mistake in CSS for #toast-container > div:hover

### ISSUE THREAD

**Issue by nickdeis** [CodeSeven/toastr#348]
I just checked out the latest version, and I noticed that 
```css
#toast-container > :hover {
  -moz-box-shadow: 0 0 12px #000000;
  -webkit-box-shadow: 0 0 12px #000000;
  box-shadow: 0 0 12px #000000;
  opacity: 1;
  -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
  filter: alpha(opacity=100);
  cursor: pointer;
}
```
This causes the hover functionality to break
Changing this to
```css
#toast-container > div:hover 
```
Seems to fix it.

Best,
Nick
