### ISSUE TITLE
how to control toast transparency?

### ISSUE THREAD

**Issue by Mo7mud** [CodeSeven/toastr#607]
Is there a way or option to control transparency level for toasts?
I want to decrease it as it's not clear enough.
Thanks.

**Comment by janhybs** [comment]
Globally, you can tweak css, you can override default `0.8` value with:
```css
body #toast-container > div {
  opacity: .4;
}
```
Individually, `info`, `success`, `warning` and `error`  methods return div object which is displayed, you can alter opacity manually.
